config/routes.rb
# routes.rb: -*- Ruby -*-  DESCRIPTIVE TEXT.
# 
# EVIXP - Generic API Server Backend for use in health studies.
#
# Copyright (C) 2019 The EVIXP Authors (See AUTHORS)
# This software is licensed under the GNU Affero General Public License, Version 3.
# Please see the file 'LICENSE' for more detailed information.
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
#  Author: Brian J. Fox (bfox@opuslogica.com)
#  Birthdate: Fri Sep  6 09:29:14 2019.
Rails.application.routes.draw do
  devise_for :crc_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  
  devise_for :administrators, path: :admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Rswag::Ui::Engine => '/docs'
  mount Rswag::Api::Engine => '/docs'

#   RailsAdmin::Engine.routes.draw do
#   end
  
  get   'healthcheck',                                    to: 'application#healthcheck'

  scope "/internal/api" do
    get  "accesstokens(/:provider_name)",                 to: 'internal#get_accesstokens'
    get  "last_measurements(/:datasource)",               to: 'internal#last_measurements'
    post "measurement/:datasource",                       to: 'internal#create_measurement'
    post "failed_tokens/:datasource",                     to: 'internal#failed_tokens'
  end
  
  scope "/app" do
    scope "/api/v1" do
      match   'authenticate'                              =>  'authentication#authenticate',       via: [:get, :post]
      match   'token-validate'                            =>  'authentication#device_authenticate', via: [:get, :post]
      get     'authorize(/:provider_name)',               to: 'oauth#authorize'
      get     'callback(/:provider_name)',                to: 'oauth#callback'
      post    'register',                                 to: 'register#create'
      post    'resend_code',                              to: 'register#resend_code'
      post    'resend-code',                              to: 'register#resend_code'
      post    'validate-code',                            to: 'register#validate'
      get     'validate-code',                            to: 'register#validate'
      get     'apps-and-devices-page',                    to: 'oauth#providers'
      get     'providers',                                to: 'oauth#providers', v2: true
      get     'apps-and-devices',                         to: 'oauth#providers'

      get     'FAQ',                                      to: 'static#faq'
      get     'faq',                                      to: 'static#faq'
      get     'faq-static',                               to: 'static#faq'
      get     'faq-dynamic',                              to: 'faq#all'
      get     'faq/:id',                                  to: 'faq#getone'
      get     'faq-categories',                           to: 'faq#categories'

      get     'device/:device_id',                        to: 'device#get'
      post    'device',                                   to: 'device#create'
      post    'push-token',                               to: 'device#set_push_token'

      get     'contact',                                  to: 'static#contact'
      get     'points',                                   to: 'static#points'
      get     'study-progress',                           to: 'user#study_progress'
      get     'profile-content',                          to: 'static#profile-content'

      get     'consent-sections',                         to: 'consent#consent_sections'
      get     'apps-sections',                            to: 'consent#apps_sections'

      post    'consent-sections',                         to: 'consent#save_answers'
      
      post    'phone-event',                              to: 'phone_events#create'

      post    'signed-consent',                           to: 'consent#create_signed_consent'

      get     'user-status',                              to: 'user#get_status'
      get     'feed',                                     to: 'user#feed'
      get     'tiles',                                    to: 'user#tiles'
      get     'metadata',                                 to: 'user#metadata'
      get     'calendar-feed(/:beg/:fin)',                to: 'user#calendar_feed'
      get     'static/feed',                              to: 'static#feed'
      post    'user-status',                              to: 'user#update_status'
      post    'register-email',                           to: 'user#register_email'

      get     'your-data',                                to: 'user#your_data'

      post   'tasks/consume-video',                       to: 'tasks#consume_video'
      get    'tasks/video-upload-url(/:video_size)',      to: 'tasks#video_upload_url'

      post   'tasks(/:task_type)',                        to: 'tasks#ingest'
      get    'tasks/external-redirect(/:tile_sched_id)',  to: 'tasks#redirect_injest'
      get    'tasks/external-redirect-done',              to: 'tasks#external_redirect_done'
      post   'task-reminder',                             to: 'tasks#set_reminder'

    end
  end

  root to: 'application#docs'
end

app/models/roster.rb
# EVIXP - Generic API Server Backend for use in health studies.
# Copyright (C) 2019 The EVIXP Authors (See AUTHORS)
# This software is licensed under the GNU Affero General Public License, Version 3.
# Please see the file 'LICENSE' for more detailed information.
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
class Roster < ApplicationRecord
  before_save :canonicalize_phone
  before_save :unique_codename
  before_save :create_crc_codes
  before_save :maybe_set_after_validation
  belongs_to  :participant, class_name: "User", required: false
  has_paper_trail
  before_save :maybe_update_participant
  after_save :update_organization
  after_save do
    # keep Roster.is_test_user and User.is_test_user in sync. Probably we want to factor out User#is_test_user at some point
    unless participant.nil?
      participant.update(is_test_user: is_test_user)
    end
  end

  delegate :study_month, to: :participant, allow_nil: true
  
  validates :phone, uniqueness: true
  
  def self.lookup(num)
    self.where(phone: Phone.canonicalize(num)).first
  end
  
  def self.generate_codename
    self.new.generate_codename
  end
  
  def self.from_hash(hash)
    roster = self.where(id: hash["id"]).first if hash["id"]
    roster ||= self.where(phone: Phone.canonicalize(hash["phone"])).first if hash["phone"]
    if not roster
      cols = self.column_names
      roster = self.new(hash.slice(*cols))
    end
    roster
  end
  
  def generate_codename
    /\w{4,6}+/.gen.capitalize + /\w{4,6}+/.gen.capitalize
  end
  
  def unique_codename
    if not self.codename
      candidate = self.generate_codename
      while self.class.where(codename: candidate).first != nil
        candidate = self.generate_codename
      end
      self.codename = candidate
    end
  end

  def regen_codename
    self.codename = nil
    self.save
  end

  def canonicalize_phone
    self.phone = Phone.canonicalize(self.phone) if self.phone
  end

  def make_digits(num, for_field)
    candidate = ""
    100.times do
      candidate = (rand(9) + 1).to_s
      candidate += (num - 1).times.map{rand(10)}.join
      hash = {}
      hash[for_field] = candidate
      if not self.class.where(hash).first
        break
      end
    end
    candidate
  end

  def user
    User.lookup(self.phone)
  end

  def update_participant
    self.participant = user if not @skip_update_participant
  end

  def maybe_update_participant
    update_participant if not self.participant_id
  end

  def user_status
    self.participant.status if self.participant
  end

  def status
    user_status
  end

  def status=(new_status)
    u = self.participant
    (u.status = new_status && save) if u
  end
      
  def crc_status
    self.user_status || self.after_phone_validation
  end
  
  def create_crc_codes
    self.empatica_id ||= make_digits(3, :empatica_id)
    self.ibdoc_id ||= make_digits(4, :ibdoc_id)
    self.bodyport_id ||= make_digits(4, :bodyport_id)
  end

  def to_s
    "Roster:#{self.phone}"
  end

  def show_phone_number
    self.phone
  end

  def api_token
    self.user.devices.where.not(api_token: nil).first.api_token rescue nil
  end
  
  def start_study(make_tile_schedule=true)
    u = self.user
    u ||= User.lookup(self.phone)
    u ||= User.create(phone: self.phone)
    self.participant_id = u.id
    self.save and self.reload
    self.participant.start_study
    self.participant.make_tile_schedule if make_tile_schedule
  end

  def study_started
    self.participant&.study_started_at
  end

  # Gets the end Date of the study for the participant.
  def study_end_date
    # Note that even though the property is named "study_ended_at," it is used to indicate when the study _will_ end
    participant = self.participant
    if participant
      participant.study_ended_at&.in_time_zone(participant.timezone)&.to_date
    end
  end

  # Set when the study will end for the user
  def study_end_date=(study_end_date)
    participant = self.participant
    date = study_end_date.to_date
    if participant && date
      participant.study_ended_at = date.in_time_zone(participant.timezone)
      participant.save
    end
  end

  def study_started=(val)
    if val
      self.start_study
    else
      if self.user
        self.user.study_started_at = nil
        self.user.save
      end
    end
    self.study_started
  end
  
  def opt_in_info
    self.participant.opt_in_answers rescue nil
  end

  def opt_in_relative_location_answer
    info = opt_in_info.select { |x| x[:question_text] == "Relative location" }.first rescue nil
    info[:answer_text] if info
  end
  
  def opt_in_sharing_options_answer
    info = opt_in_info.select { |x| x[:question_text] == "Sharing options"}.first rescue nil
    info[:answer_text] if info
  end
  
  def opt_in_future_research_contact_answer
    info = opt_in_info.select { |x| x[:question_text] == "Future research contact"}.first rescue nil
    info[:answer_text] if info
  end
  
  def last_app_access
    event = participant.phone_events.order(created_at: :desc).first rescue nil
    event.created_at if event
  end
  
  def pretty_last_app_access
    access = last_app_access
    access ? access.in_time_zone(participant.timezone).strftime("%D %T") : "Not yet opened"
  end

  def points_of_study_month(month=nil)
    participant.points_of_study_month(month) rescue 0
  end
  
  def reset
    u = self.participant
    self.participant_id = nil
    @skip_update_participant = true
    self.save
    @skip_update_participant = nil
    
    if u
      u.reset(make_schedule: false)
      u.devices.destroy_all
      u.destroy
    end
    self.reload
    self
  end

  # Here's some more tech debt.  I'll fix this someday.
  #
  #   registration
  #   studyVideo
  #   screeningQuestions
  #   consentSummaryScreens
  #   reviewConsent
  #   optInQuestions
  #   verifyEmail
  #   conclusion
  #   appsConnection
  #   dashboard
  #
  def self.states
    %w(registration studyVideo screeningQuestions consentSummaryScreens reviewConsent optInQuestions
       verifyEmail conclusion appsConnection dashboard)
  end

  # Ugh.
  def maybe_set_after_validation
    if not self.user_status
      # All users consent in the app now.
      # TODO: This shouldn't be hard-coded; it should be configurable per site
      self.after_phone_validation = "consentSummaryScreens"
    end
  end

  def update_organization
    if self.site
      org = Organization.lookup(self.site)
      if not org
        org = Organization.create(name: self.site.titleize)
        nick = self.site.downcase
        org.nicknames.where(nickname: nick).find_or_create
      end
    end
  end

  def lifetime_compliance
    compliance_since(study_started)
  end

  def compliance_since(beg=nil, fin=nil)
    beg ||= Time.zone.now - 7.days
    fin ||= Time.zone.now
    res = self.user.compliance_since(beg, fin).to_s + "%" if self.user
    res ||= "N/A"
    res
  end

  def as_json(options={})
    res = super(options)
    res[:study_started_at] = self.study_started
    res.delete(:participant_id) if options[:dump]
    res
  end
end

app/views/crc/rosters/_phone_input.html.erb
<% phone_number = Roster.find(params['id']).phone rescue nil %>
<li class="string input optional stringish" id="roster_phone_input">
  <label for="roster_phone" class="label">Phone</label>
  <input id="roster_phone" type="text" onKeyDown="replace_or_not(this)" value="<%=phone_number %>" name="roster[phone]" />
</li>
<script>
  var replaced = false;
  function replace_or_not(field) {
    if (!replaced) { replaced = true; field.value = ""; }
  }

  function maybe_fix_phone() {
    if (!replaced) {
      var field = document.getElementById("roster_phone");
      field.text = field.value = "<%= phone_number %>";
    }
  }
</script>

app/views/crc/rosters/_points_earned.html.erb
<% if user&.study_started_at %>
  <div class="points-earned">
    <h3>Points earned by study month:</h3>
    <table>
      <tr>
	<% (1..12).each do |month| %>
	  <th><%= month %></th>
	<% end %>
      </tr>
      <tr>
	<% (1..12).each do |month| %>
	  <td> <%= user.points_of_study_month(month) %> </td>
	<% end %>
      </tr>
    </table>
  </div>
<% end %>

app/views/crc/rosters/_superuser.html.erb
<form id="superuser-tile-select" method="PUT" action="/crc/rosters/<%= params['id'] %>">
  <select name="tile[]" multiple="multiple">
    <% Tile.where.not(name: nil).pluck(:name).sort.uniq.each do |name| %>
      <option value="<%=name%>"><%=TileSchedule.canonicalize_task_name(name)%></option>
    <% end %>
  </select>
  <button type="submit" value="send-tile" name="submit">Send Tile</button>
</form>

<script>
  (() => {
    'use strict';
    const querystripper = ev => {
      if (ev) { window.removeEventListener(ev.type, querystripper, true); }
      try {
        const url = new URL(location.href);
        url.searchParams.delete("tile[]");
	url.searchParams.delete("submit");
	window.history.replaceState(null, "", url);
      } catch (ex) {
	console.error("BRIAN J. FOX TOLD YOU TO LOOK FOR THIS SPECIFICALLY, OTHERWISE IGNORE IT.")
      }
    };

    if (document.readyState === 'loading') {
      window.addEventListener('DOMContentLoaded', querystripper, true);
    } else {
      querystripper();
    }
  })();
</script>

app/views/crc/rosters/_tile_schedule.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/bootstrap/main.min.css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/main.min.css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/daygrid/main.min.css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/list/main.min.css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/timegrid/main.min.css"/>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/main.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/bootstrap/main.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/daygrid/main.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/list/main.min.js"></script>

<% true %>
<div>
  (Times shown in participant's timezone)
</div>
<div id="calendar" style="max-width: 800px;"></div>

<script>
    <% user = Roster.find(params['id']).participant rescue nil %>
    var user_id = "<%= user.id if user %>";
    var calendarEl = document.getElementById('calendar');
    // The FullCalendar-moment plugin we need to adjust for timezones requires an ES build system
    // (see https://fullcalendar.io/docs/timeZone), which we don't have right now.
    // So this calendar must be fed datetimes that have been pre-adjusted for the user's timezone
    var calendar = new FullCalendar.Calendar(calendarEl, {
        plugins: ['dayGrid'],
        defaultView: 'dayGridWeek',
        timeZone: "UTC",
        events: <%= user.schedule_as_calendar_events(fin: user.study_started_at + 1.year, include: [:task, :survey], strip_tz: true).to_json.html_safe if user %>
    });
    calendar.render();
</script>

app/views/crc/rosters/_tools_panel.html.erb
<% if current_crc_user.superuser %>
  <div>
    <%= render partial: 'superuser' %>
  </div>
<% end %>

<script>
  function crc_tools_toggle_checkbox(checkbox, param) {
    var reg = new RegExp(param + "=true");
    var loc = window.location.href.replace(reg, "");
    var pfx = "?";
    loc = loc.replace("?&", "?");
    loc = loc.replace("&&", "&");

    if (checkbox.checked) {
      if (loc.indexOf("?") > -1)
	pfx = "&";
      loc = loc + pfx + param + "=true";
    }
    window.location.href = loc;
  }
    
  function toggle_schedule(checkbox) {
    crc_tools_toggle_checkbox(checkbox, "enable_schedule");
  }

  function toggle_feed(checkbox) {
    crc_tools_toggle_checkbox(checkbox, "enable_feed");
  }
</script>

<% user = Roster.find(params['id']).participant rescue nil %>

<div class="roster-show-hide">
  <% if  user&.study_started_at %>
  <input type="checkbox" name="schedule-toggle" <%= @show_tile_schedule ? 'checked' : '' %>
	  onChange="toggle_schedule(this)"> <label for="schedule-toggle">Show/Hide Schedule</label>
  <br />
  <% end %>
  <input type="checkbox" name="feed-toggle" <%= @show_feed ? 'checked' : '' %>
	  onChange="toggle_feed(this)"> <label for="feed-toggle">Show/Hide Feed Simulator</label>
</div>


<div>
  <%= render partial: 'points_earned', locals: {user: user} %>
  <% if @show_tile_schedule %>
    <%= render partial: 'tile_schedule' %>
  <% end %>
</div>

<% if current_crc_user.superuser %>
  <div>
    <% if @show_feed %>
      <%= render partial: 'view_feed' %>
    <% end %>
  </div>
<% end %>

app/views/crc/rosters/_view_feed.html.erb
<%
   user = Roster.find(params[:id]).participant rescue nil
   schedules = nil
   if user
     base = user.tile_schedules.includes(:tile).order(active_at: :desc) 
     if params[:study_day]
       beg = (user.study_started_at + (params[:study_day].to_i - 1).days).in_time_zone(user.timezone).beginning_of_day
       fin = beg.end_of_day
       base = base.where(active_at: user.study_started_at..fin).where.not("expires_at < :beg", beg: beg)
     else
       base = base.where(':date BETWEEN ACTIVE_AT AND EXPIRES_AT', date: Time.zone.now)
     end
     schedules = base
   end
%>

<link rel="stylesheet" href="/assets/devices.min.css">
<style>
  .device-screen {
    height: 100%; width: 100%; font-size: 24px; background: white;
    padding: 40px 20px 20px 20px;
    border-radius: 40px;
    overflow-y: scroll;
  }
  .tile {
    min-width:95%; padding: 40px 20px;
    box-shadow: 0px 0px 5px 5px rgba(200,200,200,0.5);
    margin-bottom: 15px;
    border-radius: 5px;
    text-align: center;
    position: relative;
  }
  
  .tile h3  { font-size: 22px; font-family: "Times-Roman" }
  .tile.completed  h3 { text-decoration: line-through; }
  .tile p { font-size: 16px; font-family: "Times-Roman" }
  .tile button {
    margin-left: auto; margin-right: auto;
    background: rgba(0,100,0, 0.8); color: white;
    font-size: 14px;
    min-width: 130px;
  }
  .tile .tile-icon {
    margin-left: auto; margin-right: auto; height: 80px; width: 80px;
  }
  .tile span.active_at, .tile span.expires_at, .tile span.completed_at, .tile span.id {
    font-size: 8px; color: black; position: absolute; top:10px; left: 10px;
  }
  .tile span.expires_at { top: 18px; }
  .tile span.completed_at { right: 10px; left: auto; }
  .tile span.id { top: auto; bottom: 10px; }
  .tile.alert-style { background-color: rgb(233,233,164); }
  span.feed-for {
    font-size: 12px; font-family: 'Helvetica', 'Arial', sans-serif;
    display: block; margin-top: 4px;
  }
</style>
<% if schedules
   current_study_day = 0 %>
<div class="device device-iphone-x" style="float: right; margin-top: -700px;">
  <div class="device-frame">
    <div class="device-screen">
      <% schedules.each do |sched|
	 tile = sched.tile
	 icon = tile.icon
	 title = tile.title
	 icon ||= "checklist"
	 completed = sched.completed_at ? "completed" : "incomplete"
	 ttype = tile.referenced_type
	 heading = nil; body = nil
	 if ttype and ttype.include?("survey")
	   heading = TileSchedule.canonicalize_task_name(tile.name)
	   body = "Please complete the survey"
	   button = "Start now"
	 elsif ttype and ttype.include?("task")
	   heading = "It's time for a #{TileSchedule.canonicalize_task_name(tile.name)} task"
	   button = "Start now"
	 else
	   property = tile.properties.where(name: "contents").first
	   prophash = JSON.parse(property.value) rescue nil
	   contents = tile.contents.first.content if tile.contents.first
           button = tile.buttons.first.label if tile.buttons.first

	   if prophash
	     heading = prophash["heading"]
	     body = prophash["body"]
	   else
	     heading = contents
	   end
         end

	 if ttype == "ema"
	   heading = "Quick Activity"
	   body = nil
	   button = nil
	 end

	 feed_for = nil
	 if sched.study_day != current_study_day
	   feed_for = "Feed for #{(user.study_started_at + (sched.study_day - 1).days).strftime('%b %-d %Y')}  (Study Day #{sched.study_day})" rescue nil
	   current_study_day = sched.study_day
         end
      %>
      <% if feed_for  %>
	<span class="feed-for"><%= feed_for %></span>
      <% end %>

      <div class="tile <%= completed %> <%= tile.style_class %>">
	<span class="active_at">A: <%= sched.active_at.in_time_zone(user.timezone) %></span>
	<span class="expires_at">E: <%= sched.expires_at.in_time_zone(user.timezone) %></span>
	<% if sched.completed_at %>
	  <span class="completed_at">C: <%= sched.completed_at.in_time_zone(user.timezone) %></span>
	<% end %>
	<% if icon && tile.style_class != "alert-style" %>
	  <img class="tile-icon" src="/assets/<%= icon %>.png" onerror="this.src='/assets/default-icon.png';this.onerror='';">
	<% end %>
	<% if title and not heading %>
	    <h3><%= title %></h3>
	<% end %>
	<% if heading %>
	  <h3><%= heading %></h3>
	<% end %>
	<% if body %>
	  <p class="tile-body"><%= body %></p>
	<% end %>
	<% if button %>
	  <button><%=button %></button>
	<% end %>
	<span class="id">ID: <%= sched.id %></span>
      </div>
     <% end %>
    </div>
  </div>
  <div class="device-stripe"></div>
  <div class="device-header"></div>
  <div class="device-sensors"></div>
  <div class="device-btns"></div>
  <div class="device-power"></div>
</div>
<% end %>